# Copy to config.ini and customize with your values.

[Settings]
RMQ_HOST = <host of the RabbitMQ server>

# REQUEUE_DELAY_SECONDS = 2.0
# REQUEUE_BACKOFF_FACTOR = 1.5
# REQUEUE_DELAY_LIMIT_SECONDS = 60.0
